# Generated by Django 6.0.7 on 2026-07-29 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('color_variant', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], default='primary', help_text='Debe calzar con CATEGORY_VARIANT_MAP en el frontend (lib/constants.ts).', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='authors/')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='content.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('reading_time_minutes', models.PositiveIntegerField(default=1, help_text='Se autocalcula al guardar si se deja en 1.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('cover_image_orientation', models.CharField(choices=[('landscape', 'Horizontal'), ('portrait', 'Vertical'), ('square', 'Cuadrada')], default='landscape', max_length=10)),
                ('has_narration', models.BooleanField(default=False)),
                ('narration_audio', models.FileField(blank=True, null=True, upload_to='narration/')),
                ('youtube_embed_url', models.URLField(blank=True)),
                ('spotify_embed_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('published', 'Publicado'), ('draft', 'Borrador'), ('scheduled', 'Programado'), ('trashed', 'Eliminado')], default='draft', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='content.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='content.category')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.region')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='content.tag')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='volumes/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volumes', to='content.author')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
