# Generated by Django 6.0.7 on 2026-07-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured_podcast_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='featured_video_url',
            field=models.URLField(blank=True),
        ),
    ]
