# Generated by Django 6.0.7 on 2026-09-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_category_featured_podcast_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(help_text='Fecha y hora de inicio del evento.')),
                ('location', models.CharField(blank=True, help_text='Ej. "Biblioteca Municipal, Arequipa" o "Transmisión por Zoom".', max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('external_url', models.URLField(blank=True, help_text='Inscripción o más información. Opcional.')),
                ('status', models.CharField(choices=[('published', 'Publicado'), ('draft', 'Borrador')], default='draft', max_length=20)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
    ]
