# Generated by Django 6.0.7 on 2026-09-21 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('cuento', 'Cuento'), ('poema', 'Poema'), ('cronica', 'Crónica')], default='poema', max_length=20)),
                ('body', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='library/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='library-audio/')),
                ('source_note', models.CharField(blank=True, help_text='De dónde sale la pieza. Ej. "de Trilce, 1922".', max_length=255)),
                ('status', models.CharField(choices=[('published', 'Publicado'), ('draft', 'Borrador'), ('trashed', 'Eliminado')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='library_pieces', to='content.author')),
                ('narrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narrated_pieces', to='content.author')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
