# Generated by Django 6.0.7 on 2026-09-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_etiquetas_cortas'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image_orientation',
            field=models.CharField(choices=[('landscape', 'Horizontal'), ('portrait', 'Vertical'), ('square', 'Cuadrada'), ('panoramic', 'Banner')], default='landscape', max_length=10),
        ),
    ]
