# Generated by Django 6.0.7 on 2026-09-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_recalcular_portadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarypiece',
            name='genre',
            field=models.CharField(choices=[('cuento', 'Cuento'), ('microcuento', 'Microcuento'), ('novela', 'Novela'), ('poema', 'Poema'), ('cronica', 'Crónica'), ('ensayo', 'Ensayo'), ('discurso', 'Discurso'), ('otros', 'Otros textos')], default='poema', max_length=20),
        ),
    ]
