# Generated by Django 6.0.7 on 2026-09-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_region_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='drop_cap',
            field=models.BooleanField(default=False, help_text='Letra capital en la primera letra del primer párrafo del cuerpo.'),
        ),
        migrations.AddField(
            model_name='librarypiece',
            name='drop_cap',
            field=models.BooleanField(default=False, help_text='Letra capital en la primera letra del primer párrafo del cuerpo.'),
        ),
    ]
