# Generated by Django 6.0.7 on 2026-10-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_region_internacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reviewed_genre',
            field=models.CharField(blank=True, choices=[('cuento', 'Cuento'), ('novela', 'Novela'), ('poesia', 'Poesía'), ('ensayo', 'Ensayo'), ('cronica', 'Crónica'), ('otros', 'Otros textos')], help_text='Género del libro reseñado, no de la reseña. Solo aplica a Crítica.', max_length=20),
        ),
    ]
